apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:
    app: witek-react-app
  ports:
      - targetPort: 8080
        protocol: TCP
        port: 8080
  type: LoadBalancer
